### PR TITLE
Fix `text` option being mandatory in top-level options

### LINKED ISSUE #26: TypeScript types: `text` is mandatory in options
Text shouldn't be mandatory in options. Currently there's a type error if `text` is omitted.

### PR DESCRIPTION
**Pull request by edenstrom**
Fixes #26

### CODE REVIEW

**Comment by sindresorhus** [comment]
You shouldn't be able to specify `text` at all in the top-level options, so would be better to use the `Omit` type. `export interface Options extends Omit<BitbarOptions, 'text'>`

Would be great if you could add a type test too.

**Comment by edenstrom** [comment]
Updated and rebased from master.

Notes:

- It's possible to add `text` to the options if the user is using JS without TS. Should we add protection against that or maybe it's fine? Why touch it if it has worked for 4 years.
- Maybe the package should be rewritten in TypeScript? Probably not worth it before the 2.0 release of bitbar though, if it gets released.

**Comment by sindresorhus** [comment]
> Should we add protection against that

Yeah, that would be great.

> Why touch it if it has worked for 4 years.

You could argue that about any kind of change. It's very unlikely anyone depends on this as it wouldn't achieve anything and adding a protection just prevents user from doing a mistake.

> Maybe the package should be rewritten in TypeScript? Probably not worth it before the 2.0 release of bitbar though, if it gets released.

Nah. I've stopped converting my project to TypeScript. TypeScript is just way too buggy.

**Comment by edenstrom** [comment]
> Yeah, that would be great.

Done and pushed. Opted for a TypeError instead of silently deleting `options.text`.

> You could argue that about any kind of change. It's very unlikely anyone depends on this as it wouldn't achieve anything and adding a protection just prevents user from doing a mistake.

True. 

> Nah. I've stopped converting my project to TypeScript. TypeScript is just way too buggy.

Oh, interested to hear the issues you've been having. A discussion for another time and place though. :)

**Pull request merged**
