### PR TITLE
Fix `href` key 

### LINKED ISSUE #11: URLs with special characters don't work
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/bitbar/issues/11)

If a URL passed to `href` has special characters, such as single quotes, ampersands, etc., then the URL ends with that character when opened via this package to BitBar.

Per [this](https://stackoverflow.com/a/39707642/420217), seems like the single quote has to be specifically escaped after the `encodeURI`:

https://github.com/sindresorhus/bitbar/blob/4abea7e002a29fec7118af85119387a4530c7a76/index.js#L34

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

#
#
#
#
 
[
<
i
m
g
 
s
r
c
=
'
h
t
t
p
s
:
/
/
a
v
a
t
a
r
s
0
.
g
i
t
h
u
b
u
s
e
r
c
o
n
t
e
n
t
.
c
o
m
/
u
/
6
1
5
3
8
1
6
?
v
=
4
'
 
a
l
t
=
'
s
a
s
i
k
a
n
t
h
5
1
3
'
 
w
i
d
t
h
=
2
4
 
h
e
i
g
h
t
=
2
4
>
 
s
a
s
i
k
a
n
t
h
5
1
3
]
(
h
t
t
p
s
:
/
/
i
s
s
u
e
h
u
n
t
.
i
o
/
u
/
s
a
s
i
k
a
n
t
h
5
1
3
)
 
h
a
s
 
b
e
e
n
 
r
e
w
a
r
d
e
d
.

### Backers (Total: $20.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($20.00)
### Submitted pull Requests
- [#19 correctly encodes special characters in the `href` option](https://issuehunt.io/r/sindresorhus/bitbar/pull/19)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/bitbar/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by garyking**
Closes #11

### CODE REVIEW

**Comment by sindresorhus** [comment]
I'll merge if you reopen https://github.com/matryer/bitbar/issues/487 It should be fixed in BitBar eventually.

**Comment by gingerbeardman** [comment]
@sindresorhus @garyking I've reopened the Bitbar issue that was referenced in a deleted comment, it includes test code, please take a look.

**Comment by garyking** [comment]
I'm not sure which repo is responsible for this issue. I've forked this library and made some changes to it for now.

**Comment by garyking** [comment]
I'll close this for now until it's figured out.

**Pull request closed without merging**
